# Generated by Django 3.2.2 on 2022-02-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=350, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=1000, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
        migrations.AlterField(
            model_name='contactsme',
            name='message',
            field=models.TextField(max_length=3000, verbose_name='Сообшение'),
        ),
    ]
