# Generated by Django 3.2.2 on 2022-02-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220228_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('img', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('stock', models.BooleanField(default=False, verbose_name='Акционный товар')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('description', models.CharField(max_length=150, verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryProduct', to='shop.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
