# Generated by Django 3.2.2 on 2022-03-09 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_auto_20220309_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bascket',
            new_name='Basket',
        ),
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
    ]
