# Generated by Django 3.2.2 on 2022-03-12 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_products_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
